/**
 * AUTO-GENERATED by scripts/generate-photo-manifest.js — do not edit.
 *
 * Mirrors the image files currently sitting in src/assets. To change any
 * of these lists, add or remove photos in the matching folder and rebuild.
 */
export const STORY_PHOTOS: Record<string, string[]> = {
  chapter1: [
    'assets/story/chapter1/1.jpeg',
    'assets/story/chapter1/2.jpeg',
    'assets/story/chapter1/3.jpeg',
    'assets/story/chapter1/4.jpeg',
    'assets/story/chapter1/5.jpeg',
  ],
  chapter2: [
    'assets/story/chapter2/1.jpeg',
  ],
  chapter3: [
    'assets/story/chapter3/1.jpeg',
    'assets/story/chapter3/2.jpeg',
    'assets/story/chapter3/3.jpeg',
    'assets/story/chapter3/4.jpeg',
  ],
  chapter4: [
    'assets/story/chapter4/1.jpg',
    'assets/story/chapter4/2.jpg',
    'assets/story/chapter4/3.jpg',
    'assets/story/chapter4/4.jpg',
  ],
  chapter5: [
    'assets/story/chapter5/1.JPG',
    'assets/story/chapter5/2.jpg',
    'assets/story/chapter5/3.jpg',
  ],
};

export const BALLOON_PHOTOS: string[] = [
  'assets/balloons/1.jpg',
  'assets/balloons/2.jpg',
  'assets/balloons/3.jpg',
  'assets/balloons/4.JPEG',
  'assets/balloons/5.JPEG',
  'assets/balloons/6.JPEG',
  'assets/balloons/7.JPEG',
  'assets/balloons/8.jpg',
  'assets/balloons/9.PNG',
  'assets/balloons/10.JPG',
  'assets/balloons/11.JPEG',
  'assets/balloons/12.jpeg',
  'assets/balloons/13.jpg',
  'assets/balloons/14.jpeg',
  'assets/balloons/15.jpg',
  'assets/balloons/16.jpg',
  'assets/balloons/17.jpg',
  'assets/balloons/18.gif',
  'assets/balloons/19.jpeg',
  'assets/balloons/20.jpg',
  'assets/balloons/21.jpg',
  'assets/balloons/22.jpg',
  'assets/balloons/23.jpg',
];

export const WALL_PHOTOS: string[] = [
  'assets/wall/1.jpg',
  'assets/wall/2.jpg',
  'assets/wall/3.jpg',
  'assets/wall/4.jpg',
  'assets/wall/5.jpg',
  'assets/wall/6.jpg',
  'assets/wall/7.jpg',
  'assets/wall/8.jpg',
  'assets/wall/9.jpg',
  'assets/wall/10.jpg',
  'assets/wall/11.jpg',
  'assets/wall/12.jpg',
  'assets/wall/13.jpg',
  'assets/wall/14.jpg',
  'assets/wall/15.jpg',
  'assets/wall/16.jpg',
  'assets/wall/17.jpg',
  'assets/wall/18.jpg',
  'assets/wall/19.jpg',
  'assets/wall/20.jpg',
  'assets/wall/21.jpg',
  'assets/wall/22.jpg',
  'assets/wall/23.jpg',
  'assets/wall/24.jpg',
  'assets/wall/25.jpg',
  'assets/wall/26.jpg',
  'assets/wall/27.jpg',
  'assets/wall/28.jpg',
  'assets/wall/29.jpg',
  'assets/wall/30.jpg',
  'assets/wall/31.jpg',
  'assets/wall/32.jpg',
  'assets/wall/33.jpg',
  'assets/wall/34.jpg',
  'assets/wall/35.jpg',
];

export const MEMORY_PHOTOS: string[] = [];
