/**
 * AUTO-GENERATED by scripts/generate-story-manifest.js — do not edit.
 *
 * Reflects whatever image files currently sit in src/assets/story/chapterN/.
 * To change it, add or remove photos in those folders and re-run the build.
 */
export const STORY_PHOTOS: Record<string, string[]> = {
  chapter1: [
    'assets/story/chapter1/1.jpeg',
    'assets/story/chapter1/2.jpeg',
    'assets/story/chapter1/3.jpeg',
    'assets/story/chapter1/4.jpeg',
    'assets/story/chapter1/5.jpeg',
  ],
  chapter2: [
    'assets/story/chapter2/1.jpeg',
  ],
  chapter3: [
    'assets/story/chapter3/1.jpeg',
    'assets/story/chapter3/2.jpeg',
    'assets/story/chapter3/3.jpeg',
    'assets/story/chapter3/4.jpeg',
  ],
  chapter4: [
    'assets/story/chapter4/1.jpg',
    'assets/story/chapter4/2.jpg',
    'assets/story/chapter4/3.jpg',
    'assets/story/chapter4/4.jpg',
  ],
  chapter5: [
    'assets/story/chapter5/1.JPG',
    'assets/story/chapter5/2.jpg',
    'assets/story/chapter5/3.jpg',
  ],
};
