/**
 * AUTO-GENERATED by scripts/generate-story-manifest.js — do not edit.
 *
 * Reflects whatever image files currently sit in src/assets/story/chapterN/.
 * To change it, add or remove photos in those folders and re-run the build.
 */
export const STORY_PHOTOS: Record<string, string[]> = {
  chapter1: [
    'assets/story/chapter1/1.jpeg',
    'assets/story/chapter1/2.jpeg',
    'assets/story/chapter1/3.jpeg',
    'assets/story/chapter1/4.jpeg',
    'assets/story/chapter1/5.jpeg',
  ],
  chapter2: [],
  chapter3: [
    'assets/story/chapter3/1.jpeg',
    'assets/story/chapter3/2.jpeg',
    'assets/story/chapter3/3.jpeg',
    'assets/story/chapter3/4.jpeg',
  ],
  chapter4: [],
  chapter5: [],
};
